build:
  os: "ubuntu-22.04"
  tools:
    python: "3.7"

sphinx:
  configuration: sphinx/source/conf.py

formats: all

python:
    version: 3.7
    use_system_site_packages: true
    pip_install: true
    extra_requirements:
        - doc
